[workspace]
resolver = "2"
members = ["crates/*"]

[workspace.package]
version = "0.1.0"
edition = "2021"

[workspace.dependencies]
anyhow = "1"
rusqlite = { version = "0.32", features = ["bundled"] }
symphonia = { version = "0.5", features = ["mp3", "flac", "wav", "ogg", "isomp4", "aac", "pcm"] }
rustfft = "6"

[profile.release]
opt-level = 3
lto = "thin"
